### PR TITLE
Implement property schema validation

### LINKED ISSUE #73: Invalid configuration encountered: unrecognized property 'logForwarding'
When running sls deploy I see the following warning:

```
❯ sls deploy --region eu-west-1 --stage tst --aws-profile my-app --verbose
Running "serverless" from node_modules

Warning: Invalid configuration encountered
  at 'functions.splunkApplicationLogging': unrecognized property 'logForwarding'

Learn more about configuration validation here: http://slss.io/configuration-validation
```
## Expected behaviour

- no warning for valid configuration properties of the plugin

## Reproduction

```serverless.yml

functions:
  splunkApplicationLogging:
    handler: src/handlers/log-forwarding/logger.handler
    logForwarding:
      # avoid a loop because this lambda ships the logs, it should not recurse itself
      enabled: false
```

## versions used
```
❯ serverless --version
Running "serverless" from node_modules
Framework Core: 3.11.0 (local) 3.19.0 (global)
Plugin: 6.2.1
SDK: 4.3.2

❯ cat package.json | grep log-forwarding
    "serverless-log-forwarding": "^3.0.1",
```

As far as the documentation of the plugin goes I have done the right things, its just the serverless framework complaining.

### PR DESCRIPTION
**Pull request by crunchie84**
Fixes #73 

TODOS
- [x] document schema
- [x] manually verify JSON schema (https://www.jsonschemavalidator.net/)[https://www.jsonschemavalidator.net/]
- [x] Verify that unit tests still run
  - I didn't see an easy way to add unit tests for the json schema 🤔
- [ ] Test that when using this version of the plugin the console warning is no longer rendered
  - If the maintainer of this repo easily can do the test that would be really great, need to figure out how to link a local version of a plugin into my codebase

### CODE REVIEW

**Review by danielharbor — COMMENTED** [review]
Hi @crunchie84, is there anything currently blocking this PR? I ask because this fix turns out to be one that my project is currently in need of.

**Comment by danielharbor** [comment]
> Hey @danielharbor I contributed this fix a long time a go. Im currently not in the position to fix the static code analysis issue in the cicd so if the maintainers can address that its LGTM and shippable

Thanks @crunchie84, we'll try to push it along.

**Comment by crunchie84** [comment]
@danielharbor I've rebased the PR on the current state of `master` and locally made the linting issues pass. Lemme know if that makes it easy for you to merge this PR

**Comment by danielharbor** [comment]
> @danielharbor I've rebased the PR on the current state of `master` and locally made the linting issues pass. Lemme know if that makes it easy for you to merge this PR

This is great to hear @crunchie84. Thank you 🥂. I'll also try to see if I can find a way to get the last item checked off:
> - [ ] Test that when using this version of the plugin the console warning is no longer rendered

@mluhovyi I do see that you've done quite a bit of work in this repo recently. Please any assistance you can offer in terms of getting the unchecked item above verified and/or reviewing the pull request would be much appreciated.

**Review by rddimon — APPROVED** [review]

**Comment by danielharbor** [comment]
FYI @g-bartoszek

**Comment by danielharbor** [comment]
Thanks, @rddimon!

**Comment by rddimon** [comment]
Hi @danielharbor!

It's not released yet
I'm still working on some improvements
But I hope we will release it this year

**Comment by danielharbor** [comment]
> Hi @danielharbor!
> 
> It's not released yet I'm still working on some improvements But I hope we will release it this year

Thanks for the heads up, @rddimon. We'll try to keep an eye out for the new release but please, in case you remember, we would appreciate an update here as well. Thanks so much!

**Pull request merged**
